nombre = input("Ingrese su nombre: ")
print(nombre)
print(type(nombre))
edad = int (input("Ingrese su edad: "))
print(edad)
print(type(edad))
#estado de matricula
estado = bool(input("Ingrese su estado de matricula: true/false "))
print(estado)
print(type(estado))
peso = float(input("Ingrese su peso: "))
print(peso)
print(type(peso))